# Generated by Django 3.2.12 on 2022-04-04 01:14

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=100)),
                ('schedule_date', models.DateTimeField(verbose_name='schedule date')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_image/Tse.png', max_length=255, null=True, upload_to=Accounts.models.profile_image_filepath),
        ),
    ]
