# Generated by Django 3.2.12 on 2022-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20220404_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=300)),
                ('schedule_date', models.DateTimeField(verbose_name='schedule date')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
