# Generated by Django 3.2.12 on 2022-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20220404_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=5, unique=True, verbose_name='Email'),
        ),
    ]
